### ISSUE TITLE
Security Hook In

### ISSUE THREAD

**Issue by Dev123213** [AOHUA/redux-state-sync#25]
Hi,

This library looks good, but do you offer a way to easily hook into when you receive a message? I envisage something like:

```javascript
const handler = msg => {
     // default is empty fn returning true, we can configure
     if ( thisLibrary.callbacks.validateMessage( msg ) ) {
         ... do redux magic
    }
}

channel.addEventListener('message', handler);
```

The reason is because I want to pass with the message a security token. The token will be the same across tabs for my user, and by checking this message token exactly matches the current users token stored elsewhere, I can be certain the message is not from a malicious source.

**Comment by AOHUA** [comment]
You should be certain that the message is not from a malicious source, because you can only get the messages from the same origin.

Right now redux-state-sync does not support callback functions on receiving messages. It could be a good feature. But need to define when the callback should be trigged.

**Comment by Dev123213** [comment]
I have gone through the code for broadcast channel and you are correct - it works per origin so i wont need this feature thanks!
